import os
from building import *

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)

# Add SDK
Import('SIFLI_SDK')
objs.extend(SConscript(os.path.join(SIFLI_SDK, 'SConscript'), variant_dir="sifli_sdk", duplicate=0))

# Add LCPU Patch
objs.extend(SConscript(os.path.join(SIFLI_SDK, 'example/rom_bin/lcpu_general_ble_img/SConscript'), variant_dir="lcpu_patch", duplicate=0))

# Add application source code
objs.extend(SConscript(cwd+'/../src/SConscript', variant_dir="src", duplicate=0))

board = GetOption('board')
if board == 'sf32lb52-xty-ai':
    print("当前开发板是 sf32lb52-xty-ai，执行相关逻辑")
    objs.extend(SConscript(cwd+'/../asset2/SConscript', variant_dir="asset2", duplicate=0))
else:
    print("当前开发板不是 sf32lb52-xty-ai，跳过编译")
    objs.extend(SConscript(cwd+'/../asset/SConscript', variant_dir="asset", duplicate=0))

Return('objs')
